# Define a PersistentVolumeClaim (PVC) for NFS
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc  # Specify the name of the PVC
spec:
  accessModes:
    - ReadWriteMany  # Define the access mode for the PVC (multiple nodes can read and write)
  resources:
    requests:
      storage: 5Gi  # Requested storage size for the PVC
  -------------------------------------------------------------------------------------------
  Explanation:

apiVersion and kind: Specify the API version and kind of the Kubernetes resource. In this case, it's v1 and PersistentVolumeClaim.

metadata: Contains metadata about the PVC, including the name (nfs-pvc in this case).

spec: Describes the desired state for the PVC.

accessModes: Specify the access mode for the PVC. In this example, it's set to ReadWriteMany, indicating that multiple nodes can read and write.

resources: Define the resource requirements for the PVC.

requests: Specify the requested storage size for the PVC. In this case, it's set to 5Gi (5 gigabytes).
