# Define a Kubernetes Service with NodePort type
apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service  # Specify the name of the Service
spec:
  type: NodePort  # Exposes the service on each node's IP at a static port
  selector:
    app: my-app  # Pods with this label will be part of the service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Port on the pods to forward traffic to
      nodePort: 30000  # Port on the nodes to access the service externally
