# Define a PersistentVolume (PV) for NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv  # Specify the name of the PV
spec:
  capacity:
    storage: 5Gi  # Total storage capacity of the PV
  accessModes:
    - ReadWriteMany  # Define the access mode for the PV (multiple nodes can read and write)
  nfs:
    server: nfs-server.example.com  # NFS server address
    path: /path/to/nfs/share  # NFS server path
-------------------------------------------------------------------------------------------------
Explanation:

apiVersion and kind: Specify the API version and kind of the Kubernetes resource. In this case, it's v1 and PersistentVolume.

metadata: Contains metadata about the PV, including the name (nfs-pv in this case).

spec: Describes the desired state for the PV.

capacity: Specify the total storage capacity of the PV. In this example, it's set to 5Gi (5 gigabytes).

accessModes: Specify the access mode for the PV. In this case, it's set to ReadWriteMany, indicating that multiple nodes can read and write.

nfs: Define NFS-specific parameters.

server: Specify the address of the NFS server.

path: Specify the path on the NFS server where the volume is exported.
