# Define a StorageClass for NFS
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-sc  # Specify the name of the StorageClass
provisioner: nfs-provisioner.example.com  # Specify the provisioner for NFS
-----------------------------------------------------------------------------
Explanation:

apiVersion and kind: Specify the API version and kind of the Kubernetes resource. In this case, it's storage.k8s.io/v1 and StorageClass.

metadata: Contains metadata about the StorageClass, including the name (nfs-sc in this case).

provisioner: Specifies the provisioner for NFS. This is typically the address or identifier of the NFS provisioner responsible for dynamically creating PVs.
